#pragma once
#include "JuceHeader.h"
#include <vector>
#include <string>




//==============================================================================
namespace material {

    template <typename T>
    static std::string bintos (const T& binary)
    {
        std::string content;
        content.reserve (sizeof (binary));
        for (auto c : binary) content += c;
        return content;
    }

    class util
    {
    public:
        static std::unique_ptr<Drawable> icon (const String& svgString, Colour colour=Colours::black)
        {
            auto svg = std::unique_ptr<XmlElement> (XmlDocument (svgString).getDocumentElement());
            auto drawable = std::unique_ptr<Drawable> (Drawable::createFromSVG (*svg));
            drawable->replaceColour (Colours::black, colour);
            return drawable;
        }

        template <typename T>
        static std::unique_ptr<Drawable> icon (const T& binary, Colour colour=Colours::black)
        {
            return icon (String (bintos (binary)), colour);
        }
    };

    class action
    {
    public:
        static const unsigned char ic_3d_rotation[1717];
        static const unsigned char ic_accessibility[200];
        static const unsigned char ic_accessible[525];
        static const unsigned char ic_account_balance[192];
        static const unsigned char ic_account_balance_wallet[316];
        static const unsigned char ic_account_box[301];
        static const unsigned char ic_account_circle[348];
        static const unsigned char ic_add_shopping_cart[520];
        static const unsigned char ic_alarm[394];
        static const unsigned char ic_alarm_add[387];
        static const unsigned char ic_alarm_off[651];
        static const unsigned char ic_alarm_on[427];
        static const unsigned char ic_all_out[356];
        static const unsigned char ic_android[656];
        static const unsigned char ic_announcement[216];
        static const unsigned char ic_aspect_ratio[262];
        static const unsigned char ic_assessment[241];
        static const unsigned char ic_assignment[340];
        static const unsigned char ic_assignment_ind[411];
        static const unsigned char ic_assignment_late[325];
        static const unsigned char ic_assignment_return[320];
        static const unsigned char ic_assignment_returned[320];
        static const unsigned char ic_assignment_turned_in[346];
        static const unsigned char ic_autorenew[355];
        static const unsigned char ic_backup[297];
        static const unsigned char ic_book[213];
        static const unsigned char ic_bookmark[172];
        static const unsigned char ic_bookmark_border[202];
        static const unsigned char ic_bug_report[494];
        static const unsigned char ic_build[291];
        static const unsigned char ic_cached[349];
        static const unsigned char ic_card_giftcard[550];
        static const unsigned char ic_card_membership[236];
        static const unsigned char ic_card_travel[307];
        static const unsigned char ic_change_history[153];
        static const unsigned char ic_check_circle[250];
        static const unsigned char ic_chrome_reader_mode[243];
        static const unsigned char ic_class[213];
        static const unsigned char ic_code[202];
        static const unsigned char ic_compare_arrows[179];
        static const unsigned char ic_copyright[897];
        static const unsigned char ic_credit_card[232];
        static const unsigned char ic_dashboard[169];
        static const unsigned char ic_date_range[279];
        static const unsigned char ic_delete[188];
        static const unsigned char ic_delete_forever[311];
        static const unsigned char ic_description[240];
        static const unsigned char ic_dns[373];
        static const unsigned char ic_done[152];
        static const unsigned char ic_done_all[260];
        static const unsigned char ic_donut_large[322];
        static const unsigned char ic_donut_small[322];
        static const unsigned char ic_euro_symbol[456];
        static const unsigned char ic_event[257];
        static const unsigned char ic_event_seat[206];
        static const unsigned char ic_exit_to_app[283];
        static const unsigned char ic_explore[321];
        static const unsigned char ic_extension[389];
        static const unsigned char ic_face[516];
        static const unsigned char ic_favorite[269];
        static const unsigned char ic_favorite_border[447];
        static const unsigned char ic_feedback[215];
        static const unsigned char ic_find_in_page[378];
        static const unsigned char ic_find_replace[431];
        static const unsigned char ic_fingerprint[1837];
        static const unsigned char ic_flight_land[290];
        static const unsigned char ic_flight_takeoff[314];
        static const unsigned char ic_flip_to_back[385];
        static const unsigned char ic_flip_to_front[332];
        static const unsigned char ic_g_translate[799];
        static const unsigned char ic_gavel[264];
        static const unsigned char ic_get_app[152];
        static const unsigned char ic_grade[198];
        static const unsigned char ic_group_work[361];
        static const unsigned char ic_help[384];
        static const unsigned char ic_highlight_off[356];
        static const unsigned char ic_history[359];
        static const unsigned char ic_home[139];
        static const unsigned char ic_hourglass_empty[188];
        static const unsigned char ic_hourglass_full[210];
        static const unsigned char ic_http[253];
        static const unsigned char ic_https[361];
        static const unsigned char ic_important_devices[555];
        static const unsigned char ic_info[202];
        static const unsigned char ic_info_outline[273];
        static const unsigned char ic_input[258];
        static const unsigned char ic_invert_colors[347];
        static const unsigned char ic_label[248];
        static const unsigned char ic_label_outline[278];
        static const unsigned char ic_language[940];
        static const unsigned char ic_launch[246];
        static const unsigned char ic_lightbulb_outline[434];
        static const unsigned char ic_line_style[273];
        static const unsigned char ic_line_weight[162];
        static const unsigned char ic_list[194];
        static const unsigned char ic_lock[361];
        static const unsigned char ic_lock_open[365];
        static const unsigned char ic_lock_outline[361];
        static const unsigned char ic_loyalty[563];
        static const unsigned char ic_markunread_mailbox[206];
        static const unsigned char ic_motorcycle[446];
        static const unsigned char ic_note_add[243];
        static const unsigned char ic_opacity[342];
        static const unsigned char ic_open_in_browser[242];
        static const unsigned char ic_open_in_new[246];
        static const unsigned char ic_open_with[223];
        static const unsigned char ic_pageview[385];
        static const unsigned char ic_pan_tool[392];
        static const unsigned char ic_payment[232];
        static const unsigned char ic_perm_camera_mic[384];
        static const unsigned char ic_perm_contact_calendar[329];
        static const unsigned char ic_perm_data_setting[848];
        static const unsigned char ic_perm_device_information[254];
        static const unsigned char ic_perm_identity[380];
        static const unsigned char ic_perm_media[288];
        static const unsigned char ic_perm_phone_msg[376];
        static const unsigned char ic_perm_scan_wifi[204];
        static const unsigned char ic_pets[638];
        static const unsigned char ic_picture_in_picture[243];
        static const unsigned char ic_picture_in_picture_alt[237];
        static const unsigned char ic_play_for_work[212];
        static const unsigned char ic_polymer[178];
        static const unsigned char ic_power_settings_new[329];
        static const unsigned char ic_pregnant_woman[237];
        static const unsigned char ic_print[263];
        static const unsigned char ic_query_builder[297];
        static const unsigned char ic_question_answer[225];
        static const unsigned char ic_receipt[259];
        static const unsigned char ic_record_voice_over[362];
        static const unsigned char ic_redeem[552];
        static const unsigned char ic_remove_shopping_cart[543];
        static const unsigned char ic_report_problem[151];
        static const unsigned char ic_restore[359];
        static const unsigned char ic_restore_page[385];
        static const unsigned char ic_room[241];
        static const unsigned char ic_rounded_corner[346];
        static const unsigned char ic_rowing[457];
        static const unsigned char ic_schedule[297];
        static const unsigned char ic_search[317];
        static const unsigned char ic_settings[787];
        static const unsigned char ic_settings_applications[867];
        static const unsigned char ic_settings_backup_restore[347];
        static const unsigned char ic_settings_bluetooth[334];
        static const unsigned char ic_settings_brightness[316];
        static const unsigned char ic_settings_cell[266];
        static const unsigned char ic_settings_ethernet[298];
        static const unsigned char ic_settings_input_antenna[419];
        static const unsigned char ic_settings_input_component[469];
        static const unsigned char ic_settings_input_composite[469];
        static const unsigned char ic_settings_input_hdmi[220];
        static const unsigned char ic_settings_input_svideo[552];
        static const unsigned char ic_settings_overscan[311];
        static const unsigned char ic_settings_phone[405];
        static const unsigned char ic_settings_power[379];
        static const unsigned char ic_settings_remote[488];
        static const unsigned char ic_settings_voice[371];
        static const unsigned char ic_shop[238];
        static const unsigned char ic_shop_two[292];
        static const unsigned char ic_shopping_basket[416];
        static const unsigned char ic_shopping_cart[462];
        static const unsigned char ic_speaker_notes[280];
        static const unsigned char ic_speaker_notes_off[360];
        static const unsigned char ic_spellcheck[260];
        static const unsigned char ic_stars[286];
        static const unsigned char ic_store[181];
        static const unsigned char ic_subject[167];
        static const unsigned char ic_supervisor_account[402];
        static const unsigned char ic_swap_horiz[177];
        static const unsigned char ic_swap_vert[176];
        static const unsigned char ic_swap_vertical_circle[225];
        static const unsigned char ic_system_update_alt[258];
        static const unsigned char ic_tab[213];
        static const unsigned char ic_tab_unselected[397];
        static const unsigned char ic_theaters[249];
        static const unsigned char ic_thumb_down[347];
        static const unsigned char ic_thumb_up[353];
        static const unsigned char ic_thumbs_up_down[527];
        static const unsigned char ic_timeline[548];
        static const unsigned char ic_toc[195];
        static const unsigned char ic_today[254];
        static const unsigned char ic_toll[344];
        static const unsigned char ic_touch_app[509];
        static const unsigned char ic_track_changes[549];
        static const unsigned char ic_translate[402];
        static const unsigned char ic_trending_down[179];
        static const unsigned char ic_trending_flat[124];
        static const unsigned char ic_trending_up[179];
        static const unsigned char ic_turned_in[172];
        static const unsigned char ic_turned_in_not[202];
        static const unsigned char ic_update[402];
        static const unsigned char ic_verified_user[229];
        static const unsigned char ic_view_agenda[255];
        static const unsigned char ic_view_array[154];
        static const unsigned char ic_view_carousel[153];
        static const unsigned char ic_view_column[156];
        static const unsigned char ic_view_day[209];
        static const unsigned char ic_view_headline[164];
        static const unsigned char ic_view_list[198];
        static const unsigned char ic_view_module[209];
        static const unsigned char ic_view_quilt[174];
        static const unsigned char ic_view_stream[135];
        static const unsigned char ic_view_week[333];
        static const unsigned char ic_visibility[328];
        static const unsigned char ic_visibility_off[629];
        static const unsigned char ic_watch_later[231];
        static const unsigned char ic_work[263];
        static const unsigned char ic_youtube_searched_for[398];
        static std::vector<std::string> icons();
        static std::string find (const std::string& icon);
    };
    class alert
    {
    public:
        static const unsigned char ic_add_alert[375];
        static const unsigned char ic_error[201];
        static const unsigned char ic_error_outline[277];
        static const unsigned char ic_warning[151];
        static std::vector<std::string> icons();
        static std::string find (const std::string& icon);
    };
    class av
    {
    public:
        static const unsigned char ic_add_to_queue[265];
        static const unsigned char ic_airplay[219];
        static const unsigned char ic_album[276];
        static const unsigned char ic_art_track[292];
        static const unsigned char ic_av_timer[466];
        static const unsigned char ic_branding_watermark[201];
        static const unsigned char ic_call_to_action[199];
        static const unsigned char ic_closed_caption[393];
        static const unsigned char ic_equalizer[152];
        static const unsigned char ic_explicit[228];
        static const unsigned char ic_fast_forward[143];
        static const unsigned char ic_fast_rewind[143];
        static const unsigned char ic_featured_play_list[215];
        static const unsigned char ic_featured_video[201];
        static const unsigned char ic_fiber_dvr[385];
        static const unsigned char ic_fiber_manual_record[161];
        static const unsigned char ic_fiber_new[379];
        static const unsigned char ic_fiber_pin[325];
        static const unsigned char ic_fiber_smart_record[274];
        static const unsigned char ic_forward_10[662];
        static const unsigned char ic_forward_30[1163];
        static const unsigned char ic_forward_5[608];
        static const unsigned char ic_games[196];
        static const unsigned char ic_hearing[677];
        static const unsigned char ic_high_quality[339];
        static const unsigned char ic_library_add[268];
        static const unsigned char ic_library_books[283];
        static const unsigned char ic_library_music[314];
        static const unsigned char ic_loop[347];
        static const unsigned char ic_mic[325];
        static const unsigned char ic_mic_none[447];
        static const unsigned char ic_mic_off[483];
        static const unsigned char ic_movie[225];
        static const unsigned char ic_music_video[320];
        static const unsigned char ic_new_releases[317];
        static const unsigned char ic_not_interested[350];
        static const unsigned char ic_note[207];
        static const unsigned char ic_pause[137];
        static const unsigned char ic_pause_circle_filled[203];
        static const unsigned char ic_pause_circle_outline[272];
        static const unsigned char ic_play_arrow[117];
        static const unsigned char ic_play_circle_filled[189];
        static const unsigned char ic_play_circle_filled_white[201];
        static const unsigned char ic_play_circle_outline[258];
        static const unsigned char ic_playlist_add[185];
        static const unsigned char ic_playlist_add_check[191];
        static const unsigned char ic_playlist_play[212];
        static const unsigned char ic_queue[268];
        static const unsigned char ic_queue_music[237];
        static const unsigned char ic_queue_play_next[266];
        static const unsigned char ic_radio[321];
        static const unsigned char ic_recent_actors[359];
        static const unsigned char ic_remove_from_queue[246];
        static const unsigned char ic_repeat[170];
        static const unsigned char ic_repeat_one[195];
        static const unsigned char ic_replay_10[660];
        static const unsigned char ic_replay_30[1158];
        static const unsigned char ic_replay[226];
        static const unsigned char ic_replay_5[604];
        static const unsigned char ic_shuffle[273];
        static const unsigned char ic_skip_next[141];
        static const unsigned char ic_skip_previous[131];
        static const unsigned char ic_slow_motion_video[653];
        static const unsigned char ic_snooze[402];
        static const unsigned char ic_stop[117];
        static const unsigned char ic_subscriptions[252];
        static const unsigned char ic_subtitles[255];
        static const unsigned char ic_surround_sound[587];
        static const unsigned char ic_video_call[230];
        static const unsigned char ic_video_label[200];
        static const unsigned char ic_video_library[251];
        static const unsigned char ic_videocam[194];
        static const unsigned char ic_videocam_off[258];
        static const unsigned char ic_volume_down[191];
        static const unsigned char ic_volume_mute[130];
        static const unsigned char ic_volume_off[472];
        static const unsigned char ic_volume_up[301];
        static const unsigned char ic_web[250];
        static const unsigned char ic_web_asset[220];
        static std::vector<std::string> icons();
        static std::string find (const std::string& icon);
    };
    class communication
    {
    public:
        static const unsigned char ic_business[316];
        static const unsigned char ic_call[354];
        static const unsigned char ic_call_end[527];
        static const unsigned char ic_call_made[150];
        static const unsigned char ic_call_merge[200];
        static const unsigned char ic_call_missed[160];
        static const unsigned char ic_call_missed_outgoing[165];
        static const unsigned char ic_call_received[149];
        static const unsigned char ic_call_split[208];
        static const unsigned char ic_chat[236];
        static const unsigned char ic_chat_bubble[175];
        static const unsigned char ic_chat_bubble_outline[197];
        static const unsigned char ic_clear_all[152];
        static const unsigned char ic_comment[236];
        static const unsigned char ic_contact_mail[364];
        static const unsigned char ic_contact_phone[496];
        static const unsigned char ic_contacts[368];
        static const unsigned char ic_dialer_sip[440];
        static const unsigned char ic_dialpad[684];
        static const unsigned char ic_email[232];
        static const unsigned char ic_forum[225];
        static const unsigned char ic_import_contacts[421];
        static const unsigned char ic_import_export[176];
        static const unsigned char ic_invert_colors_off[498];
        static const unsigned char ic_live_help[415];
        static const unsigned char ic_location_off[419];
        static const unsigned char ic_location_on[241];
        static const unsigned char ic_mail_outline[246];
        static const unsigned char ic_message[233];
        static const unsigned char ic_no_sim[271];
        static const unsigned char ic_phone[354];
        static const unsigned char ic_portable_wifi_off[778];
        static const unsigned char ic_present_to_all[245];
        static const unsigned char ic_ring_volume[664];
        static const unsigned char ic_rss_feed[296];
        static const unsigned char ic_screen_share[295];
        static const unsigned char ic_speaker_phone[519];
        static const unsigned char ic_stay_current_landscape[221];
        static const unsigned char ic_stay_current_portrait[230];
        static const unsigned char ic_stay_primary_landscape[221];
        static const unsigned char ic_stay_primary_portrait[230];
        static const unsigned char ic_stop_screen_share[451];
        static const unsigned char ic_swap_calls[270];
        static const unsigned char ic_textsms[230];
        static const unsigned char ic_voicemail[387];
        static const unsigned char ic_vpn_key[273];
        static std::vector<std::string> icons();
        static std::string find (const std::string& icon);
    };
    class content
    {
    public:
        static const unsigned char ic_add[142];
        static const unsigned char ic_add_box[229];
        static const unsigned char ic_add_circle[206];
        static const unsigned char ic_add_circle_outline[275];
        static const unsigned char ic_archive[344];
        static const unsigned char ic_backspace[342];
        static const unsigned char ic_block[346];
        static const unsigned char ic_clear[210];
        static const unsigned char ic_content_copy[247];
        static const unsigned char ic_content_cut[533];
        static const unsigned char ic_content_paste[315];
        static const unsigned char ic_create[244];
        static const unsigned char ic_delete_sweep[221];
        static const unsigned char ic_drafts[264];
        static const unsigned char ic_filter_list[151];
        static const unsigned char ic_flag[142];
        static const unsigned char ic_forward[130];
        static const unsigned char ic_gesture[786];
        static const unsigned char ic_inbox[258];
        static const unsigned char ic_link[331];
        static const unsigned char ic_low_priority[247];
        static const unsigned char ic_mail[232];
        static const unsigned char ic_markunread[232];
        static const unsigned char ic_move_to_inbox[287];
        static const unsigned char ic_next_week[321];
        static const unsigned char ic_redo[253];
        static const unsigned char ic_remove[119];
        static const unsigned char ic_remove_circle[187];
        static const unsigned char ic_remove_circle_outline[256];
        static const unsigned char ic_reply[163];
        static const unsigned char ic_reply_all[196];
        static const unsigned char ic_report[292];
        static const unsigned char ic_save[255];
        static const unsigned char ic_select_all[441];
        static const unsigned char ic_send[138];
        static const unsigned char ic_sort[149];
        static const unsigned char ic_text_format[201];
        static const unsigned char ic_unarchive[347];
        static const unsigned char ic_undo[248];
        static const unsigned char ic_weekend[346];
        static std::vector<std::string> icons();
        static std::string find (const std::string& icon);
    };
    class device
    {
    public:
        static const unsigned char ic_access_alarm[394];
        static const unsigned char ic_access_alarms[359];
        static const unsigned char ic_access_time[297];
        static const unsigned char ic_add_alarm[387];
        static const unsigned char ic_airplanemode_active[219];
        static const unsigned char ic_airplanemode_inactive[268];
        static const unsigned char ic_battery_20[295];
        static const unsigned char ic_battery_30[296];
        static const unsigned char ic_battery_50[296];
        static const unsigned char ic_battery_60[296];
        static const unsigned char ic_battery_80[296];
        static const unsigned char ic_battery_90[296];
        static const unsigned char ic_battery_alert[280];
        static const unsigned char ic_battery_charging_20[333];
        static const unsigned char ic_battery_charging_30[330];
        static const unsigned char ic_battery_charging_50[347];
        static const unsigned char ic_battery_charging_60[333];
        static const unsigned char ic_battery_charging_80[334];
        static const unsigned char ic_battery_charging_90[335];
        static const unsigned char ic_battery_charging_full[276];
        static const unsigned char ic_battery_full[247];
        static const unsigned char ic_battery_std[247];
        static const unsigned char ic_battery_unknown[483];
        static const unsigned char ic_bluetooth[290];
        static const unsigned char ic_bluetooth_connected[337];
        static const unsigned char ic_bluetooth_disabled[309];
        static const unsigned char ic_bluetooth_searching[508];
        static const unsigned char ic_brightness_auto[294];
        static const unsigned char ic_brightness_high[340];
        static const unsigned char ic_brightness_low[282];
        static const unsigned char ic_brightness_medium[257];
        static const unsigned char ic_data_usage[401];
        static const unsigned char ic_developer_mode[381];
        static const unsigned char ic_devices[247];
        static const unsigned char ic_dvr[294];
        static const unsigned char ic_gps_fixed[407];
        static const unsigned char ic_gps_not_fixed[349];
        static const unsigned char ic_gps_off[563];
        static const unsigned char ic_graphic_eq[182];
        static const unsigned char ic_location_disabled[582];
        static const unsigned char ic_location_searching[362];
        static const unsigned char ic_network_cell[157];
        static const unsigned char ic_network_wifi[324];
        static const unsigned char ic_nfc[358];
        static const unsigned char ic_screen_lock_landscape[390];
        static const unsigned char ic_screen_lock_portrait[388];
        static const unsigned char ic_screen_lock_rotation[635];
        static const unsigned char ic_screen_rotation[545];
        static const unsigned char ic_sd_storage[220];
        static const unsigned char ic_settings_system_daydream[358];
        static const unsigned char ic_signal_cellular_0_bar[130];
        static const unsigned char ic_signal_cellular_1_bar[157];
        static const unsigned char ic_signal_cellular_2_bar[157];
        static const unsigned char ic_signal_cellular_3_bar[157];
        static const unsigned char ic_signal_cellular_4_bar[112];
        static const unsigned char ic_signal_cellular_connected_no_internet_0_bar[185];
        static const unsigned char ic_signal_cellular_connected_no_internet_1_bar[203];
        static const unsigned char ic_signal_cellular_connected_no_internet_2_bar[203];
        static const unsigned char ic_signal_cellular_connected_no_internet_3_bar[202];
        static const unsigned char ic_signal_cellular_connected_no_internet_4_bar[155];
        static const unsigned char ic_signal_cellular_no_sim[271];
        static const unsigned char ic_signal_cellular_null[144];
        static const unsigned char ic_signal_cellular_off[189];
        static const unsigned char ic_signal_wifi_0_bar[214];
        static const unsigned char ic_signal_wifi_1_bar[318];
        static const unsigned char ic_signal_wifi_1_bar_lock[469];
        static const unsigned char ic_signal_wifi_2_bar[314];
        static const unsigned char ic_signal_wifi_2_bar_lock[459];
        static const unsigned char ic_signal_wifi_3_bar[324];
        static const unsigned char ic_signal_wifi_3_bar_lock[489];
        static const unsigned char ic_signal_wifi_4_bar[188];
        static const unsigned char ic_signal_wifi_4_bar_lock[389];
        static const unsigned char ic_signal_wifi_off[297];
        static const unsigned char ic_storage[189];
        static const unsigned char ic_usb[402];
        static const unsigned char ic_wallpaper[353];
        static const unsigned char ic_widgets[205];
        static const unsigned char ic_wifi_lock[361];
        static const unsigned char ic_wifi_tethering[566];
        static std::vector<std::string> icons();
        static std::string find (const std::string& icon);
    };
    class editor
    {
    public:
        static const unsigned char ic_attach_file[323];
        static const unsigned char ic_attach_money[443];
        static const unsigned char ic_border_all[190];
        static const unsigned char ic_border_bottom[363];
        static const unsigned char ic_border_clear[424];
        static const unsigned char ic_border_color[274];
        static const unsigned char ic_border_horizontal[362];
        static const unsigned char ic_border_inner[324];
        static const unsigned char ic_border_left[369];
        static const unsigned char ic_border_outer[215];
        static const unsigned char ic_border_right[364];
        static const unsigned char ic_border_style[233];
        static const unsigned char ic_border_top[370];
        static const unsigned char ic_border_vertical[364];
        static const unsigned char ic_bubble_chart[196];
        static const unsigned char ic_drag_handle[134];
        static const unsigned char ic_format_align_center[182];
        static const unsigned char ic_format_align_justify[176];
        static const unsigned char ic_format_align_left[180];
        static const unsigned char ic_format_align_right[181];
        static const unsigned char ic_format_bold[312];
        static const unsigned char ic_format_clear[247];
        static const unsigned char ic_format_color_fill[403];
        static const unsigned char ic_format_color_reset[331];
        static const unsigned char ic_format_color_text[224];
        static const unsigned char ic_format_indent_decrease[201];
        static const unsigned char ic_format_indent_increase[200];
        static const unsigned char ic_format_italic[153];
        static const unsigned char ic_format_line_spacing[190];
        static const unsigned char ic_format_list_bulleted[324];
        static const unsigned char ic_format_list_numbered[246];
        static const unsigned char ic_format_paint[232];
        static const unsigned char ic_format_quote[148];
        static const unsigned char ic_format_shapes[357];
        static const unsigned char ic_format_size[153];
        static const unsigned char ic_format_strikethrough[160];
        static const unsigned char ic_format_textdirection_l_to_r[189];
        static const unsigned char ic_format_textdirection_r_to_l[192];
        static const unsigned char ic_format_underlined[214];
        static const unsigned char ic_functions[150];
        static const unsigned char ic_highlight[234];
        static const unsigned char ic_insert_chart[241];
        static const unsigned char ic_insert_comment[225];
        static const unsigned char ic_insert_drive_file[207];
        static const unsigned char ic_insert_emoticon[436];
        static const unsigned char ic_insert_invitation[257];
        static const unsigned char ic_insert_link[331];
        static const unsigned char ic_insert_photo[225];
        static const unsigned char ic_linear_scale[367];
        static const unsigned char ic_merge_type[200];
        static const unsigned char ic_mode_comment[186];
        static const unsigned char ic_mode_edit[244];
        static const unsigned char ic_monetization_on[544];
        static const unsigned char ic_multiline_chart[372];
        static const unsigned char ic_pie_chart[243];
        static const unsigned char ic_pie_chart_outlined[315];
        static const unsigned char ic_publish[148];
        static const unsigned char ic_short_text[126];
        static const unsigned char ic_show_chart[164];
        static const unsigned char ic_space_bar[127];
        static const unsigned char ic_strikethrough_s[1181];
        static const unsigned char ic_text_fields[153];
        static const unsigned char ic_title[125];
        static const unsigned char ic_vertical_align_bottom[146];
        static const unsigned char ic_vertical_align_center[172];
        static const unsigned char ic_vertical_align_top[143];
        static const unsigned char ic_wrap_text[230];
        static std::vector<std::string> icons();
        static std::string find (const std::string& icon);
    };
    class file
    {
    public:
        static const unsigned char ic_attachment[317];
        static const unsigned char ic_cloud[264];
        static const unsigned char ic_cloud_circle[291];
        static const unsigned char ic_cloud_done[323];
        static const unsigned char ic_cloud_download[294];
        static const unsigned char ic_cloud_off[483];
        static const unsigned char ic_cloud_queue[389];
        static const unsigned char ic_cloud_upload[297];
        static const unsigned char ic_create_new_folder[245];
        static const unsigned char ic_file_download[152];
        static const unsigned char ic_file_upload[143];
        static const unsigned char ic_folder[207];
        static const unsigned char ic_folder_open[225];
        static const unsigned char ic_folder_shared[310];
        static std::vector<std::string> icons();
        static std::string find (const std::string& icon);
    };
    class hardware
    {
    public:
        static const unsigned char ic_cast[319];
        static const unsigned char ic_cast_connected[374];
        static const unsigned char ic_computer[228];
        static const unsigned char ic_desktop_mac[226];
        static const unsigned char ic_desktop_windows[227];
        static const unsigned char ic_developer_board[294];
        static const unsigned char ic_devices_other[414];
        static const unsigned char ic_dock[239];
        static const unsigned char ic_gamepad[196];
        static const unsigned char ic_headset[247];
        static const unsigned char ic_headset_mic[257];
        static const unsigned char ic_keyboard[372];
        static const unsigned char ic_keyboard_arrow_down[155];
        static const unsigned char ic_keyboard_arrow_left[156];
        static const unsigned char ic_keyboard_arrow_right[155];
        static const unsigned char ic_keyboard_arrow_up[151];
        static const unsigned char ic_keyboard_backspace[163];
        static const unsigned char ic_keyboard_capslock[178];
        static const unsigned char ic_keyboard_hide[389];
        static const unsigned char ic_keyboard_return[168];
        static const unsigned char ic_keyboard_tab[190];
        static const unsigned char ic_keyboard_voice[325];
        static const unsigned char ic_laptop[211];
        static const unsigned char ic_laptop_chromebook[162];
        static const unsigned char ic_laptop_mac[309];
        static const unsigned char ic_laptop_windows[233];
        static const unsigned char ic_memory[320];
        static const unsigned char ic_mouse[231];
        static const unsigned char ic_phone_android[227];
        static const unsigned char ic_phone_iphone[266];
        static const unsigned char ic_phonelink[247];
        static const unsigned char ic_phonelink_off[346];
        static const unsigned char ic_power_input[167];
        static const unsigned char ic_router[511];
        static const unsigned char ic_scanner[301];
        static const unsigned char ic_security[241];
        static const unsigned char ic_sim_card[294];
        static const unsigned char ic_smartphone[221];
        static const unsigned char ic_speaker[386];
        static const unsigned char ic_speaker_group[443];
        static const unsigned char ic_tablet[219];
        static const unsigned char ic_tablet_android[227];
        static const unsigned char ic_tablet_mac[264];
        static const unsigned char ic_toys[263];
        static const unsigned char ic_tv[228];
        static const unsigned char ic_videogame_asset[342];
        static const unsigned char ic_watch[319];
        static std::vector<std::string> icons();
        static std::string find (const std::string& icon);
    };
    class iconfont
    {
    public:
        static std::vector<std::string> icons();
        static std::string find (const std::string& icon);
    };
    class image
    {
    public:
        static const unsigned char ic_add_a_photo[373];
        static const unsigned char ic_add_to_photos[268];
        static const unsigned char ic_adjust[296];
        static const unsigned char ic_assistant[278];
        static const unsigned char ic_assistant_photo[142];
        static const unsigned char ic_audiotrack[201];
        static const unsigned char ic_blur_circular[853];
        static const unsigned char ic_blur_linear[753];
        static const unsigned char ic_blur_off[1339];
        static const unsigned char ic_blur_on[1342];
        static const unsigned char ic_brightness_1[121];
        static const unsigned char ic_brightness_2[236];
        static const unsigned char ic_brightness_3[239];
        static const unsigned char ic_brightness_4[337];
        static const unsigned char ic_brightness_5[282];
        static const unsigned char ic_brightness_6[257];
        static const unsigned char ic_brightness_7[340];
        static const unsigned char ic_broken_image[245];
        static const unsigned char ic_brush[301];
        static const unsigned char ic_burst_mode[243];
        static const unsigned char ic_camera[546];
        static const unsigned char ic_camera_alt[316];
        static const unsigned char ic_camera_front[358];
        static const unsigned char ic_camera_rear[303];
        static const unsigned char ic_camera_roll[336];
        static const unsigned char ic_center_focus_strong[316];
        static const unsigned char ic_center_focus_weak[374];
        static const unsigned char ic_collections[267];
        static const unsigned char ic_color_lens[504];
        static const unsigned char ic_colorize[326];
        static const unsigned char ic_compare[250];
        static const unsigned char ic_control_point[275];
        static const unsigned char ic_control_point_duplicate[390];
        static const unsigned char ic_crop_16_9[211];
        static const unsigned char ic_crop_3_2[210];
        static const unsigned char ic_crop[201];
        static const unsigned char ic_crop_5_4[211];
        static const unsigned char ic_crop_7_5[211];
        static const unsigned char ic_crop_din[210];
        static const unsigned char ic_crop_free[256];
        static const unsigned char ic_crop_landscape[211];
        static const unsigned char ic_crop_original[263];
        static const unsigned char ic_crop_portrait[210];
        static const unsigned char ic_crop_rotate[419];
        static const unsigned char ic_crop_square[210];
        static const unsigned char ic_dehaze[149];
        static const unsigned char ic_details[147];
        static const unsigned char ic_edit[244];
        static const unsigned char ic_exposure[261];
        static const unsigned char ic_exposure_neg_1[160];
        static const unsigned char ic_exposure_neg_2[740];
        static const unsigned char ic_exposure_plus_1[180];
        static const unsigned char ic_exposure_plus_2[760];
        static const unsigned char ic_exposure_zero[911];
        static const unsigned char ic_filter_1[270];
        static const unsigned char ic_filter_2[340];
        static const unsigned char ic_filter_3[358];
        static const unsigned char ic_filter[301];
        static const unsigned char ic_filter_4[281];
        static const unsigned char ic_filter_5[322];
        static const unsigned char ic_filter_6[365];
        static const unsigned char ic_filter_7[278];
        static const unsigned char ic_filter_8[446];
        static const unsigned char ic_filter_9[362];
        static const unsigned char ic_filter_9_plus[393];
        static const unsigned char ic_filter_b_and_w[225];
        static const unsigned char ic_filter_center_focus[316];
        static const unsigned char ic_filter_drama[426];
        static const unsigned char ic_filter_frames[254];
        static const unsigned char ic_filter_hdr[164];
        static const unsigned char ic_filter_none[248];
        static const unsigned char ic_filter_tilt_shift[818];
        static const unsigned char ic_filter_vintage[783];
        static const unsigned char ic_flare[438];
        static const unsigned char ic_flash_auto[205];
        static const unsigned char ic_flash_off[207];
        static const unsigned char ic_flash_on[129];
        static const unsigned char ic_flip[321];
        static const unsigned char ic_gradient[367];
        static const unsigned char ic_grain[567];
        static const unsigned char ic_grid_off[443];
        static const unsigned char ic_grid_on[330];
        static const unsigned char ic_hdr_off[341];
        static const unsigned char ic_hdr_on[296];
        static const unsigned char ic_hdr_strong[289];
        static const unsigned char ic_hdr_weak[288];
        static const unsigned char ic_healing[763];
        static const unsigned char ic_image[225];
        static const unsigned char ic_image_aspect_ratio[272];
        static const unsigned char ic_iso[265];
        static const unsigned char ic_landscape[164];
        static const unsigned char ic_leak_add[375];
        static const unsigned char ic_leak_remove[691];
        static const unsigned char ic_lens[169];
        static const unsigned char ic_linked_camera[441];
        static const unsigned char ic_looks_3[309];
        static const unsigned char ic_looks[278];
        static const unsigned char ic_looks_4[225];
        static const unsigned char ic_looks_5[266];
        static const unsigned char ic_looks_6[308];
        static const unsigned char ic_looks_one[216];
        static const unsigned char ic_looks_two[283];
        static const unsigned char ic_loupe[294];
        static const unsigned char ic_monochrome_photos[753];
        static const unsigned char ic_movie_creation[225];
        static const unsigned char ic_movie_filter[366];
        static const unsigned char ic_music_note[190];
        static const unsigned char ic_nature[232];
        static const unsigned char ic_nature_people[338];
        static const unsigned char ic_navigate_before[151];
        static const unsigned char ic_navigate_next[151];
        static const unsigned char ic_palette[504];
        static const unsigned char ic_panorama[224];
        static const unsigned char ic_panorama_fish_eye[238];
        static const unsigned char ic_panorama_horizontal[542];
        static const unsigned char ic_panorama_vertical[550];
        static const unsigned char ic_panorama_wide_angle[569];
        static const unsigned char ic_photo[225];
        static const unsigned char ic_photo_album[252];
        static const unsigned char ic_photo_camera[316];
        static const unsigned char ic_photo_filter[317];
        static const unsigned char ic_photo_library[267];
        static const unsigned char ic_picture_as_pdf[404];
        static const unsigned char ic_portrait[354];
        static const unsigned char ic_remove_red_eye[320];
        static const unsigned char ic_rotate_90_degrees_ccw[473];
        static const unsigned char ic_rotate_left[482];
        static const unsigned char ic_rotate_right[481];
        static const unsigned char ic_slideshow[230];
        static const unsigned char ic_straighten[244];
        static const unsigned char ic_style[497];
        static const unsigned char ic_switch_camera[253];
        static const unsigned char ic_switch_video[238];
        static const unsigned char ic_tag_faces[436];
        static const unsigned char ic_texture[408];
        static const unsigned char ic_timelapse[360];
        static const unsigned char ic_timer_10[2024];
        static const unsigned char ic_timer_3[2237];
        static const unsigned char ic_timer[377];
        static const unsigned char ic_timer_off[606];
        static const unsigned char ic_tonality[473];
        static const unsigned char ic_transform[223];
        static const unsigned char ic_tune[233];
        static const unsigned char ic_view_comfy[292];
        static const unsigned char ic_view_compact[153];
        static const unsigned char ic_wb_auto[364];
        static const unsigned char ic_wb_cloudy[264];
        static const unsigned char ic_wb_incandescent[363];
        static const unsigned char ic_wb_iridescent[361];
        static const unsigned char ic_wb_sunny[450];
        static std::vector<std::string> icons();
        static std::string find (const std::string& icon);
    };
    class maps
    {
    public:
        static const unsigned char ic_add_location[219];
        static const unsigned char ic_beenhere[294];
        static const unsigned char ic_directions[294];
        static const unsigned char ic_directions_bike[589];
        static const unsigned char ic_directions_boat[581];
        static const unsigned char ic_directions_bus[397];
        static const unsigned char ic_directions_car[403];
        static const unsigned char ic_directions_railway[269];
        static const unsigned char ic_directions_run[361];
        static const unsigned char ic_directions_subway[354];
        static const unsigned char ic_directions_transit[354];
        static const unsigned char ic_directions_walk[330];
        static const unsigned char ic_edit_location[310];
        static const unsigned char ic_ev_station[460];
        static const unsigned char ic_flight[219];
        static const unsigned char ic_hotel[216];
        static const unsigned char ic_layers[218];
        static const unsigned char ic_layers_clear[344];
        static const unsigned char ic_local_activity[390];
        static const unsigned char ic_local_airport[198];
        static const unsigned char ic_local_atm[333];
        static const unsigned char ic_local_bar[184];
        static const unsigned char ic_local_cafe[227];
        static const unsigned char ic_local_car_wash[609];
        static const unsigned char ic_local_convenience_store[208];
        static const unsigned char ic_local_dining[394];
        static const unsigned char ic_local_drink[291];
        static const unsigned char ic_local_florist[628];
        static const unsigned char ic_local_gas_station[449];
        static const unsigned char ic_local_grocery_store[462];
        static const unsigned char ic_local_hospital[237];
        static const unsigned char ic_local_hotel[216];
        static const unsigned char ic_local_laundry_service[451];
        static const unsigned char ic_local_library[278];
        static const unsigned char ic_local_mall[366];
        static const unsigned char ic_local_movies[249];
        static const unsigned char ic_local_offer[367];
        static const unsigned char ic_local_parking[201];
        static const unsigned char ic_local_pharmacy[210];
        static const unsigned char ic_local_phone[354];
        static const unsigned char ic_local_pizza[293];
        static const unsigned char ic_local_play[390];
        static const unsigned char ic_local_post_office[232];
        static const unsigned char ic_local_printshop[263];
        static const unsigned char ic_local_see[316];
        static const unsigned char ic_local_shipping[350];
        static const unsigned char ic_local_taxi[413];
        static const unsigned char ic_map[305];
        static const unsigned char ic_my_location[407];
        static const unsigned char ic_navigation[147];
        static const unsigned char ic_near_me[149];
        static const unsigned char ic_person_pin[353];
        static const unsigned char ic_person_pin_circle[340];
        static const unsigned char ic_pin_drop[247];
        static const unsigned char ic_place[241];
        static const unsigned char ic_rate_review[293];
        static const unsigned char ic_restaurant[239];
        static const unsigned char ic_restaurant_menu[394];
        static const unsigned char ic_satellite[322];
        static const unsigned char ic_store_mall_directory[181];
        static const unsigned char ic_streetview[379];
        static const unsigned char ic_subway[459];
        static const unsigned char ic_terrain[164];
        static const unsigned char ic_traffic[535];
        static const unsigned char ic_train[362];
        static const unsigned char ic_tram[376];
        static const unsigned char ic_transfer_within_a_station[406];
        static const unsigned char ic_zoom_out_map[321];
        static std::vector<std::string> icons();
        static std::string find (const std::string& icon);
    };
    class navigation
    {
    public:
        static const unsigned char ic_apps[242];
        static const unsigned char ic_arrow_back[167];
        static const unsigned char ic_arrow_downward[183];
        static const unsigned char ic_arrow_drop_down[120];
        static const unsigned char ic_arrow_drop_down_circle[188];
        static const unsigned char ic_arrow_drop_up[120];
        static const unsigned char ic_arrow_forward[161];
        static const unsigned char ic_arrow_upward[165];
        static const unsigned char ic_cancel[287];
        static const unsigned char ic_check[152];
        static const unsigned char ic_chevron_left[151];
        static const unsigned char ic_chevron_right[151];
        static const unsigned char ic_close[210];
        static const unsigned char ic_expand_less[149];
        static const unsigned char ic_expand_more[152];
        static const unsigned char ic_first_page[166];
        static const unsigned char ic_fullscreen[192];
        static const unsigned char ic_fullscreen_exit[191];
        static const unsigned char ic_last_page[167];
        static const unsigned char ic_menu[149];
        static const unsigned char ic_more_horiz[277];
        static const unsigned char ic_more_vert[275];
        static const unsigned char ic_refresh[315];
        static const unsigned char ic_subdirectory_arrow_left[170];
        static const unsigned char ic_subdirectory_arrow_right[247];
        static const unsigned char ic_unfold_less[233];
        static const unsigned char ic_unfold_more[227];
        static std::vector<std::string> icons();
        static std::string find (const std::string& icon);
    };
    class notification
    {
    public:
        static const unsigned char ic_adb[453];
        static const unsigned char ic_airline_seat_flat[289];
        static const unsigned char ic_airline_seat_flat_angled[374];
        static const unsigned char ic_airline_seat_individual_suite[207];
        static const unsigned char ic_airline_seat_legroom_extra[337];
        static const unsigned char ic_airline_seat_legroom_normal[260];
        static const unsigned char ic_airline_seat_legroom_reduced[298];
        static const unsigned char ic_airline_seat_recline_extra[570];
        static const unsigned char ic_airline_seat_recline_normal[508];
        static const unsigned char ic_bluetooth_audio[508];
        static const unsigned char ic_confirmation_number[326];
        static const unsigned char ic_disc_full[261];
        static const unsigned char ic_do_not_disturb[350];
        static const unsigned char ic_do_not_disturb_alt[315];
        static const unsigned char ic_do_not_disturb_off[374];
        static const unsigned char ic_do_not_disturb_on[187];
        static const unsigned char ic_drive_eta[400];
        static const unsigned char ic_enhanced_encryption[325];
        static const unsigned char ic_event_available[312];
        static const unsigned char ic_event_busy[365];
        static const unsigned char ic_event_note[274];
        static const unsigned char ic_folder_special[292];
        static const unsigned char ic_live_tv[273];
        static const unsigned char ic_mms[215];
        static const unsigned char ic_more[401];
        static const unsigned char ic_network_check[613];
        static const unsigned char ic_network_locked[334];
        static const unsigned char ic_no_encryption[375];
        static const unsigned char ic_ondemand_video[244];
        static const unsigned char ic_personal_video[228];
        static const unsigned char ic_phone_bluetooth_speaker[531];
        static const unsigned char ic_phone_forwarded[385];
        static const unsigned char ic_phone_in_talk[458];
        static const unsigned char ic_phone_locked[525];
        static const unsigned char ic_phone_missed[554];
        static const unsigned char ic_phone_paused[388];
        static const unsigned char ic_power[220];
        static const unsigned char ic_priority_high[146];
        static const unsigned char ic_rv_hookup[320];
        static const unsigned char ic_sd_card[220];
        static const unsigned char ic_sim_card_alert[209];
        static const unsigned char ic_sms[230];
        static const unsigned char ic_sms_failed[215];
        static const unsigned char ic_sync[347];
        static const unsigned char ic_sync_disabled[564];
        static const unsigned char ic_sync_problem[403];
        static const unsigned char ic_system_update[251];
        static const unsigned char ic_tap_and_play[383];
        static const unsigned char ic_time_to_leave[400];
        static const unsigned char ic_vibration[277];
        static const unsigned char ic_voice_chat[222];
        static const unsigned char ic_vpn_lock[615];
        static const unsigned char ic_wc[376];
        static const unsigned char ic_wifi[276];
        static std::vector<std::string> icons();
        static std::string find (const std::string& icon);
    };
    class places
    {
    public:
        static const unsigned char ic_ac_unit[391];
        static const unsigned char ic_airport_shuttle[373];
        static const unsigned char ic_all_inclusive[677];
        static const unsigned char ic_beach_access[443];
        static const unsigned char ic_business_center[324];
        static const unsigned char ic_casino[481];
        static const unsigned char ic_child_care[976];
        static const unsigned char ic_child_friendly[472];
        static const unsigned char ic_fitness_center[364];
        static const unsigned char ic_free_breakfast[224];
        static const unsigned char ic_golf_course[281];
        static const unsigned char ic_hot_tub[737];
        static const unsigned char ic_kitchen[268];
        static const unsigned char ic_pool[1514];
        static const unsigned char ic_room_service[262];
        static const unsigned char ic_rv_hookup[320];
        static const unsigned char ic_smoke_free[478];
        static const unsigned char ic_smoking_rooms[470];
        static const unsigned char ic_spa[678];
        static std::vector<std::string> icons();
        static std::string find (const std::string& icon);
    };
    class social
    {
    public:
        static const unsigned char ic_cake[683];
        static const unsigned char ic_domain[316];
        static const unsigned char ic_group[389];
        static const unsigned char ic_group_add[467];
        static const unsigned char ic_location_city[277];
        static const unsigned char ic_mood[436];
        static const unsigned char ic_mood_bad[419];
        static const unsigned char ic_notifications[282];
        static const unsigned char ic_notifications_active[497];
        static const unsigned char ic_notifications_none[326];
        static const unsigned char ic_notifications_off[486];
        static const unsigned char ic_notifications_paused[335];
        static const unsigned char ic_pages[280];
        static const unsigned char ic_party_mode[449];
        static const unsigned char ic_people[389];
        static const unsigned char ic_people_outline[608];
        static const unsigned char ic_person[228];
        static const unsigned char ic_person_add[264];
        static const unsigned char ic_person_outline[380];
        static const unsigned char ic_plus_one[159];
        static const unsigned char ic_poll[241];
        static const unsigned char ic_public[423];
        static const unsigned char ic_school[183];
        static const unsigned char ic_sentiment_dissatisfied[483];
        static const unsigned char ic_sentiment_neutral[391];
        static const unsigned char ic_sentiment_satisfied[484];
        static const unsigned char ic_sentiment_very_dissatisfied[551];
        static const unsigned char ic_sentiment_very_satisfied[425];
        static const unsigned char ic_share[477];
        static const unsigned char ic_whatshot[406];
        static std::vector<std::string> icons();
        static std::string find (const std::string& icon);
    };
    class sprites
    {
    public:
        static std::vector<std::string> icons();
        static std::string find (const std::string& icon);
    };
    class toggle
    {
    public:
        static const unsigned char ic_check_box[248];
        static const unsigned char ic_check_box_outline_blank[209];
        static const unsigned char ic_radio_button_checked[309];
        static const unsigned char ic_radio_button_unchecked[238];
        static const unsigned char ic_star_half[278];
        static std::vector<std::string> icons();
        static std::string find (const std::string& icon);
    };
}
